Repository OpenSIPS/opensips, pull requests merged in 2023-05, with the labels that each got.

#2915 dialog: try to get a options/reinvite last direction
  modules/dialog/dlg_timer.c
Labels: improvement

#3086 add inhert_state param for mi dr_reload
  mi/item.c
  mi/item.h
  modules/dispatcher/dispatch.c
  modules/dispatcher/dispatch.h
  modules/dispatcher/dispatcher.c
  modules/drouting/doc/drouting_admin.xml
  modules/drouting/drouting.c
Labels: improvement

#3070 Fix: regex segfault if max_groups is exceeded
  modules/regex/regex_mod.c
Labels: investigating

#3084 Add options to set_dlg_profile and unset_dlg_profile to remove all values on a profile
  modules/dialog/dialog.c
  modules/dialog/dlg_profile.c
  modules/dialog/dlg_profile.h
  modules/dialog/doc/dialog_admin.xml
Labels: new feature
