Repository OpenSIPS/opensips, pull requests merged in 2025-02, with the labels that each got.

#3590 Fix dbid password special chars
  db/db_id.c
  db/test/test_db.c
Labels: improvement

#3575 Fix avpops memory leak in avp_db_load / avp_db_delete / avp_db_store (for 3.4)
  modules/avpops/avpops.c
Labels: bug

#3576 Fix sqlops memory leak in sql_avp_load / sql_avp_delete / sql_avp_store (for 3.5 and master)
  modules/sqlops/sqlops.c
Labels: bug

#3533 Initial version of Janus module
  db/schema/janus.xml
  db/schema/opensips-janus.xml
  modules/janus/Makefile
  modules/janus/README
  modules/janus/doc/janus.xml
  modules/janus/doc/janus_admin.xml
  modules/janus/janus_common.c
  modules/janus/janus_common.h
  modules/janus/janus_mod.c
  modules/janus/janus_parser.c
  modules/janus/janus_parser.h
  modules/janus/janus_proc.c
  modules/janus/janus_proc.h
  modules/janus/janus_ws.c
  modules/janus/janus_ws.h
  modules/janus/ws_common.h
  modules/janus/ws_common_defs.h
  modules/janus/ws_handshake_common.h
  modules/janus/ws_tcp.c
  modules/janus/ws_tcp.h
  scripts/db_berkeley/opensips/janus
  scripts/dbtext/opensips/janus
  scripts/mysql/janus-create.sql
  scripts/oracle/janus-create.sql
  scripts/pi_http/janus-mod
  scripts/pi_http/janus-table
  scripts/pi_http/pi_framework.xml
  scripts/postgres/janus-create.sql
  scripts/sqlite/janus-create.sql
Labels: new feature
