Repository OpenSIPS/opensips, pull requests merged in 2025-04, with the labels that each got.

#3501 New rtp.io module (embedded RTPProxy)
  .github/workflows/.rtp.io.yml
  .github/workflows/main.yml
  .github/workflows/rtp.io.yml
  .github/workflows/unittests.yml
  Makefile.conf.template
  Makefile.defs
  docker/Dockerfile.rtp.io
  io_wait.h
  modules/osp/timeapi.c
  modules/rtp.io/Makefile
  modules/rtp.io/doc/contributors.xml
  modules/rtp.io/doc/rtp.io.xml
  modules/rtp.io/doc/rtp.io_admin.xml
  modules/rtp.io/rtp_io.c
  modules/rtp.io/rtp_io.h
  modules/rtp.io/rtp_io_api.h
  modules/rtp.io/rtp_io_host.c
  modules/rtp.io/rtp_io_host.h
  modules/rtp.io/rtp_io_params.c
  modules/rtp.io/rtp_io_params.h
  modules/rtp.io/rtp_io_util.c
  modules/rtp.io/rtp_io_util.h
  modules/rtpproxy/rtppn_connect.c
  modules/rtpproxy/rtpproxy.c
  modules/rtpproxy/rtpproxy.h
  modules/stir_shaken/stir_shaken.c
  scripts/build/do_build.sh
  scripts/build/get-arch-buildargs.rtp.io
  scripts/build/install_depends.sh
  transformations.c
Labels: new feature

#3629 fix tls_mgm release domain issue
  modules/tls_mgm/tls_domain.c
Labels: bug, fixed

#3630 Fix CI issues (#3501 fallout)
  .github/workflows/.rtp.io.yml
  .github/workflows/unittests.yml
  modules/b2b_entities/dlg.c
  modules/cpl_c/cpl_switches.h
  modules/sqlops/sqlops_impl.c
  scripts/build/build_libtap.sh
  scripts/build/build_test_harness.sh
  scripts/build/do_build.sh
  scripts/build/dockerize.sub
  scripts/build/get-arch-buildargs.rtp.io
  scripts/build/install_depends.sh
  scripts/build/print_ccache_stats.sh
  scripts/build/zero_ccache_stats.sh
  transformations.c
Labels: improvement

#3550 Add onreply_route async capabilities
  modules/tm/async.c
  modules/tm/t_reply.c
  modules/tm/t_reply.h
Labels: new feature
