Repository OpenSIPS/opensips, pull requests merged in 2025-03, with the labels that each got.

#3528 fix: update cloned msg under lock to avoid races with branch injection
  modules/tm/tm.c
Labels: bug

#3532 rtpengine: Update fd when node reconnects
  modules/rtpengine/rtpengine.c
Labels: stale

#3571 New TOS (per socket) options
  cfg.lex
  cfg.y
  ip_addr.h
  modules/cgrates/cgrates_engine.c
  modules/janus/ws_common.h
  modules/proto_ws/ws_common.h
  net/net_tcp.c
  net/net_tcp.h
  net/net_udp.c
  net/tcp_common.c
  net/tcp_common.h
  socket_info.c
  socket_info.h
Labels: improvement

#3594 Fix sql_query required parameters
  modules/sqlops/sqlops.c
Labels: bug

#3599 Ensure proper memory deallocation in case of parsing errors
  parser/msg_parser.c
Labels: bug

#3600 Add min_ttl parameter to dns_cache
  modules/dns_cache/dns_cache.c
  modules/dns_cache/doc/dns_cache_admin.xml
Labels: new feature

#3610 Fix pointer type on 32-bin ix86 machines
  modules/aaa_diameter/aaa_diameter.c
Labels: improvement

#3613 Fix: cachedb_redis initialization fails checking for JSON support in …
  modules/cachedb_redis/cachedb_redis_dbase.c
Labels: improvement
